server:
  port: 8090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
